### ISSUE TITLE
Building guides for Android development

### ISSUE THREAD

**Issue by xplshn** [FWGS/hlsdk-portable#360]
There are no guides for Android, at least, I haven't found one, looking trough reddit, Google nor Duckduckgo, being that Android is supported, It'd be nice to have a guide, also, a build for Fdroid

**Comment by TheKingFireS** [comment]
Because you have to create your own launcher yourself

**Comment by a1batross** [comment]
Well, we do indeed lack the proper documentation for Android development right now.

At this moment, you can use FWGS/mod-sample repository as a base, but it contains outdated code that's used for Old Engine(0.19 and older) branch. The New Engine(0.20+) uses different intent string because we migrated to 64-bit on Android.

**Comment by nekonomicon** [comment]
There guide:
https://github.com/FWGS/xash3d-fwgs/issues/140

**Comment by xplshn** [comment]
Thx, really useful, hope Xash3D continues to rock, your project is awesome!

**Comment by stephen-cusi** [comment]
[basic android project](https://github.com/FWGS/hlsdk-portable/commit/d57b3fade73aa42f1a04d6311a23c3676d6b72e7)
